---
- name: Converge Tailnet management role
  hosts: all
  become: true
  vars:
    vpn:
      enable_tailnet_management: true
    tailnet_management:
      install_package: false
      package_version: "1.102.3"
      repository_gpg_sha256: "3e03dacf222698c60b8e2f990b809ca1b3e104de127767864284e6c228f1fb39"
      approved_sources:
        - 100.64.10.20
        - fd7a:115c:a1e0::1234
  roles:
    - role: tailnet-management
