---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Reload amneziawg
  ansible.builtin.command:
    cmd: awg syncconf {{ item.name }} {{ amneziawg_config_dir }}/{{ item.name }}.conf
  loop: "{{ _awg_instances | default([{'name': amneziawg.interface}]) }}"
  loop_control:
    label: "{{ item.name }}"
  changed_when: true
