---
- name: Reload nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded

- name: Restart vpn-bootstrap
  ansible.builtin.systemd_service:
    name: vpn-bootstrap.service
    state: restarted
    daemon_reload: true

- name: Restart vpn-sub-mirror timer
  ansible.builtin.systemd_service:
    name: vpn-sub-mirror.timer
    state: restarted
    daemon_reload: true
