---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart Xray stats exporter timer
  ansible.builtin.systemd_service:
    name: xray-stats-exporter.timer
    state: restarted
  when: monitoring_role_enabled | default(true) | bool and not ansible_check_mode

- name: Restart node_exporter
  ansible.builtin.systemd_service:
    name: prometheus-node-exporter
    state: restarted
  when: monitoring_role_enabled | default(true) | bool and (not ansible_check_mode or not _monitoring_node_exporter_package.changed)

- name: Restart journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted
