---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Reload xray geodata
  ansible.builtin.command:
    cmd: /usr/local/sbin/vpn-xray-geodata-activate.sh
  changed_when: true
