---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart snell
  ansible.builtin.systemd_service:
    name: snell.service
    state: restarted
  when: snell_role_enabled | default(true) | bool and not ansible_check_mode
