"""Cloud-init must publish its completion marker only after SSH reload succeeds."""

from __future__ import annotations

import base64
from collections.abc import Iterator
import errno
import importlib.util
import os
import shlex
import signal
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import pytest
import yaml


REPO_ROOT = Path(__file__).resolve().parents[2]
TEMPLATE = REPO_ROOT / "terraform" / "shared" / "cloud-init.yaml.tftpl"
RENDERER = REPO_ROOT / "scripts" / "render-cloud-init-ci.py"
BOOTSTRAP_OWNER = REPO_ROOT / "terraform" / "shared" / "bootstrap-sshd-ownership.py"
MARKER = "/var/lib/cloud-init-vpn-bootstrap.done"
BOOT = "10-cloud-init-hardening.conf"
MANAGED = "20-ansible-hardening.conf"
CLOUD = "50-cloud-init.conf"


def _write_sshd_stub(
    directory: Path,
    *,
    output: bytes | None = None,
    exit_code: int = 0,
    delay: float = 0,
    argument_log: Path | None = None,
) -> Path:
    stub = directory / f"sshd-stub-{len(tuple(directory.glob('sshd-stub-*')))}"
    if output is None:
        output_command = """config=''
while [ "$#" -gt 0 ]; do
  if [ "$1" = '-f' ]; then config=$2; shift 2; else shift; fi
done
port=$(awk '$1 == "Port" { print $2 }' "${config%/*}/sshd_config.d/10-cloud-init-hardening.conf")
printf 'port %s\\npasswordauthentication no\\nkbdinteractiveauthentication no\\npermitrootlogin no\\npubkeyauthentication yes\\nx11forwarding no\\n' "$port"
"""
    else:
        output_command = "printf %s " + shlex.quote(output.decode("ascii")) + "\n"
    log_command = ""
    if argument_log is not None:
        log_command = "printf '%s\\n' \"$@\" > " + shlex.quote(str(argument_log)) + "\n"
    stub.write_text(
        "#!/bin/sh\n"
        + log_command
        + (f"sleep {delay}\n" if delay else "")
        + output_command
        + f"exit {exit_code}\n",
        encoding="ascii",
    )
    stub.chmod(0o755)
    return stub


@pytest.fixture
def bootstrap_owner(monkeypatch: pytest.MonkeyPatch, tmp_path: Path):
    spec = importlib.util.spec_from_file_location("bootstrap_sshd_ownership", BOOTSTRAP_OWNER)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    monkeypatch.setattr(module, "OWNER_UID", os.geteuid())
    monkeypatch.setattr(module, "OWNER_GID", os.getegid())
    monkeypatch.setattr(module, "SSHD", str(_write_sshd_stub(tmp_path)), raising=False)
    return module


@pytest.fixture
def ssh_config() -> Iterator[Path]:
    # The production helper intentionally rejects writable ancestors such as
    # /tmp.  Anchor its filesystem tests below HOME so Linux pytest tmp roots
    # do not turn that fail-closed check into a platform-dependent failure.
    with tempfile.TemporaryDirectory(
        prefix=".bootstrap-sshd-test-", dir=Path.home()
    ) as directory:
        root = Path(directory)
        root.chmod(0o700)
        config = root / "etc" / "ssh"
        fragments = config / "sshd_config.d"
        fragments.mkdir(parents=True)
        main = config / "sshd_config"
        main.write_bytes(b"# packaged main\nInclude /etc/ssh/sshd_config.d/*.conf\n")
        main.chmod(0o644)
        yield config


def _records(config: Path) -> dict[str, tuple[bytes, int, int]]:
    paths = [config / "sshd_config", *(config / "sshd_config.d").iterdir()]
    return {
        str(path.relative_to(config)): (
            path.read_bytes(),
            path.stat().st_mode,
            path.stat().st_ino,
        )
        for path in paths
    }


def _rollback_records(config: Path) -> dict[str, tuple[bytes, int, int, int]]:
    paths = [config / "sshd_config", *(config / "sshd_config.d").iterdir()]
    return {
        str(path.relative_to(config)): (
            path.read_bytes(),
            path.stat().st_mode,
            path.stat().st_uid,
            path.stat().st_gid,
        )
        for path in paths
    }


def test_fresh_bootstrap_publishes_exact_single_owner_fragments_and_is_idempotent(
    bootstrap_owner, ssh_config: Path,
) -> None:
    cloud = ssh_config / "sshd_config.d" / CLOUD
    cloud.write_bytes(b"# generated by cloud-init\n\nPasswordAuthentication no\n# retained\n")
    cloud.chmod(0o640)
    main_before = (ssh_config / "sshd_config").read_bytes()

    assert bootstrap_owner.normalize(ssh_config, "2222") is True
    fragments = ssh_config / "sshd_config.d"
    assert (fragments / BOOT).read_bytes() == (
        b"Port 2222\n"
        b"PasswordAuthentication no\n"
        b"KbdInteractiveAuthentication no\n"
        b"PermitRootLogin no\n"
        b"PubkeyAuthentication yes\n"
    )
    assert (fragments / MANAGED).read_bytes() == (
        b"# first-boot runtime owner\nX11Forwarding no\n"
    )
    assert cloud.read_bytes() == b"# generated by cloud-init\n\n# retained\n"
    assert (cloud.stat().st_mode & 0o777) == 0o640
    assert (ssh_config / "sshd_config").read_bytes() == main_before

    after = _records(ssh_config)
    assert bootstrap_owner.normalize(ssh_config, "2222") is False
    assert _records(ssh_config) == after


def test_existing_exact_owner_with_noncanonical_mode_refuses_before_writes(
    bootstrap_owner, ssh_config: Path,
) -> None:
    assert bootstrap_owner.normalize(ssh_config, "22") is True
    boot = ssh_config / "sshd_config.d" / BOOT
    boot.chmod(0o600)
    before = _records(ssh_config)

    with pytest.raises(bootstrap_owner.BootstrapOwnershipError, match="unsafe-existing-owner"):
        bootstrap_owner.normalize(ssh_config, "22")

    assert _records(ssh_config) == before


@pytest.mark.parametrize(
    "main_content,error",
    [
        (b"# packaged main\n", "noncanonical-include"),
        (b"# Include /etc/ssh/sshd_config.d/*.conf\n", "noncanonical-include"),
        (b"Include sshd_config.d/*.conf\n", "noncanonical-include"),
        (b"Match User deploy\nInclude /etc/ssh/sshd_config.d/*.conf\n", "unsupported-match"),
        (b"Match=User deploy\nInclude /etc/ssh/sshd_config.d/*.conf\n", "unsupported-match"),
        (b"Match = User deploy\nInclude /etc/ssh/sshd_config.d/*.conf\n", "unsupported-match"),
        (b"Include=/etc/ssh/sshd_config.d/*.conf\n", "noncanonical-include"),
        (b"Include = /etc/ssh/sshd_config.d/*.conf\n", "noncanonical-include"),
        ((
            b"Include /etc/ssh/sshd_config.d/*.conf\n"
            b"Match all\nInclude /etc/ssh/sshd_config.d/*.conf\n"
        ), "unsupported-match"),
    ],
    ids=[
        "missing",
        "commented",
        "relative",
        "conditional",
        "conditional-equals",
        "conditional-spaced-equals",
        "include-equals",
        "include-spaced-equals",
        "after-match",
    ],
)
def test_noncanonical_top_level_include_refuses_before_writes(
    bootstrap_owner, ssh_config: Path, main_content: bytes, error: str,
) -> None:
    (ssh_config / "sshd_config").write_bytes(main_content)
    before = _records(ssh_config)

    with pytest.raises(bootstrap_owner.BootstrapOwnershipError, match=error):
        bootstrap_owner.normalize(ssh_config, "22")

    assert _records(ssh_config) == before
    assert not (ssh_config / "sshd_config.d" / BOOT).exists()
    assert not (ssh_config / "sshd_config.d" / MANAGED).exists()


def test_active_match_after_canonical_include_refuses_before_writes(
    bootstrap_owner, ssh_config: Path,
) -> None:
    (ssh_config / "sshd_config").write_bytes(
        b"Include /etc/ssh/sshd_config.d/*.conf\n"
        b"Match User deploy\nX11Forwarding yes\n"
    )
    before = _records(ssh_config)

    with pytest.raises(bootstrap_owner.BootstrapOwnershipError, match="unsupported-match"):
        bootstrap_owner.normalize(ssh_config, "22")

    assert _records(ssh_config) == before


def test_unexpected_conf_fragment_refuses_before_writes(
    bootstrap_owner, ssh_config: Path,
) -> None:
    unexpected = ssh_config / "sshd_config.d" / "90-third-party.conf"
    unexpected.write_bytes(b"# even comments are outside bootstrap ownership\n")
    unexpected.chmod(0o644)
    before = _records(ssh_config)

    with pytest.raises(bootstrap_owner.BootstrapOwnershipError, match="unsupported-membership"):
        bootstrap_owner.normalize(ssh_config, "22")

    assert _records(ssh_config) == before
    assert not (ssh_config / "sshd_config.d" / BOOT).exists()
    assert not (ssh_config / "sshd_config.d" / MANAGED).exists()


def test_commented_match_and_non_conf_entries_remain_outside_ownership(
    bootstrap_owner, ssh_config: Path,
) -> None:
    main = ssh_config / "sshd_config"
    main.write_bytes(
        b"# Match User deploy\n"
        b"# Include relative.conf\n"
        b"Include /etc/ssh/sshd_config.d/*.conf\n"
    )
    note = ssh_config / "sshd_config.d" / "README.bootstrap"
    note.write_bytes(b"not parsed by sshd\n")
    note.chmod(0o644)

    assert bootstrap_owner.normalize(ssh_config, "22") is True

    assert note.read_bytes() == b"not parsed by sshd\n"


@pytest.mark.parametrize(
    "cloud_content",
    [
        b"PermitRootLogin no\n",
        b"PasswordAuthentication no\nPasswordAuthentication no\n",
        b"PasswordAuthentication yes\n",
        b" PasswordAuthentication no\n",
    ],
    ids=["unknown", "duplicate", "value", "noncanonical"],
)
def test_unknown_cloud_ownership_refuses_before_any_write(
    bootstrap_owner, ssh_config: Path, cloud_content: bytes,
) -> None:
    cloud = ssh_config / "sshd_config.d" / CLOUD
    cloud.write_bytes(cloud_content)
    cloud.chmod(0o644)
    before = _records(ssh_config)

    with pytest.raises(bootstrap_owner.BootstrapOwnershipError):
        bootstrap_owner.normalize(ssh_config, "22")

    assert _records(ssh_config) == before
    assert not (ssh_config / "sshd_config.d" / BOOT).exists()
    assert not (ssh_config / "sshd_config.d" / MANAGED).exists()


def test_symlinked_owned_fragment_refuses_before_any_write(
    bootstrap_owner, ssh_config: Path,
) -> None:
    external = ssh_config.parent / "external"
    external.write_bytes(b"PasswordAuthentication no\n")
    (ssh_config / "sshd_config.d" / CLOUD).symlink_to(external)
    before = external.read_bytes()

    with pytest.raises(bootstrap_owner.BootstrapOwnershipError):
        bootstrap_owner.normalize(ssh_config, "22")

    assert external.read_bytes() == before
    assert not (ssh_config / "sshd_config.d" / BOOT).exists()
    assert not (ssh_config / "sshd_config.d" / MANAGED).exists()


def test_publish_failure_rolls_back_every_fragment(
    bootstrap_owner, ssh_config: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    fragments = ssh_config / "sshd_config.d"
    (fragments / CLOUD).write_bytes(b"# cloud\nPasswordAuthentication no\n")
    (fragments / CLOUD).chmod(0o644)
    before = _records(ssh_config)
    real_replace = bootstrap_owner.os.replace
    calls = 0

    def fail_second_publish(source, destination, *args, **kwargs):
        nonlocal calls
        calls += 1
        if calls == 2:
            raise OSError("injected publish failure")
        return real_replace(source, destination, *args, **kwargs)

    monkeypatch.setattr(bootstrap_owner.os, "replace", fail_second_publish)
    with pytest.raises(bootstrap_owner.BootstrapOwnershipError, match="publish-failed"):
        bootstrap_owner.normalize(ssh_config, "22")

    assert _records(ssh_config) == before
    assert not tuple(fragments.glob(".bootstrap-sshd-*"))


@pytest.mark.parametrize(
    "output,exit_code,delay,error",
    [
        (
            b"port 22\npasswordauthentication no\nkbdinteractiveauthentication no\n"
            b"permitrootlogin no\npubkeyauthentication yes\nx11forwarding yes\n",
            0,
            0,
            "effective-policy-mismatch",
        ),
        (b"", 1, 0, "effective-validation-failed"),
        (b"", 0, 1, "effective-validation-timeout"),
    ],
    ids=["mismatch", "failure", "timeout"],
)
def test_effective_validation_failure_rolls_back_without_configuration_output(
    bootstrap_owner,
    ssh_config: Path,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
    output: bytes,
    exit_code: int,
    delay: float,
    error: str,
) -> None:
    cloud = ssh_config / "sshd_config.d" / CLOUD
    cloud.write_bytes(b"# cloud\nPasswordAuthentication no\n")
    cloud.chmod(0o640)
    before = _rollback_records(ssh_config)
    monkeypatch.setattr(
        bootstrap_owner,
        "SSHD",
        str(_write_sshd_stub(tmp_path, output=output, exit_code=exit_code, delay=delay)),
        raising=False,
    )
    monkeypatch.setattr(
        bootstrap_owner,
        "COMMAND_TIMEOUT",
        0.05 if delay else 5.0,
        raising=False,
    )
    if exit_code:
        monkeypatch.setattr(bootstrap_owner.os, "killpg", lambda *_args: None)

    with pytest.raises(bootstrap_owner.BootstrapOwnershipError, match=error):
        bootstrap_owner.normalize(ssh_config, "22")

    assert _rollback_records(ssh_config) == before
    assert "x11forwarding yes" not in capsys.readouterr().err


def test_effective_validation_is_bounded_and_receives_only_the_main_config(
    bootstrap_owner, ssh_config: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    argument_log = tmp_path / "arguments"
    monkeypatch.setattr(
        bootstrap_owner,
        "SSHD",
        str(_write_sshd_stub(tmp_path, argument_log=argument_log)),
        raising=False,
    )

    assert bootstrap_owner.normalize(ssh_config, "2200") is True

    assert argument_log.read_text().splitlines() == [
        "-T",
        "-f",
        str(ssh_config / "sshd_config"),
    ]


def test_effective_runner_never_polls_or_reaps_before_terminating_owned_group(
    bootstrap_owner, ssh_config: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    events: list[str] = []
    real_popen = bootstrap_owner.subprocess.Popen
    real_killpg = bootstrap_owner.os.killpg

    class ObservedProcess:
        def __init__(self, process):
            self._process = process
            self.stdout = process.stdout
            self.pid = process.pid

        def poll(self):
            events.append("poll")
            return self._process.poll()

        def wait(self, *args, **kwargs):
            events.append("wait")
            return self._process.wait(*args, **kwargs)

    def observed_popen(*args, **kwargs):
        return ObservedProcess(real_popen(*args, **kwargs))

    def observed_killpg(*args, **kwargs):
        events.append("killpg")
        return real_killpg(*args, **kwargs)

    monkeypatch.setattr(bootstrap_owner.subprocess, "Popen", observed_popen)
    monkeypatch.setattr(bootstrap_owner.os, "killpg", observed_killpg)

    assert bootstrap_owner.normalize(ssh_config, "22") is True

    assert events[0] == "killpg"
    assert "poll" not in events
    assert events[-1] == "wait"


def test_effective_runner_accepts_eperm_only_after_natural_zero_exit(
    bootstrap_owner, monkeypatch: pytest.MonkeyPatch,
) -> None:
    class NaturalExit:
        pid = 123456
        wait_calls = 0

        def wait(self, *, timeout):
            assert timeout == 1
            self.wait_calls += 1
            return 0

    process = NaturalExit()

    def refuse_group_signal(_pid, _signal):
        raise PermissionError(errno.EPERM, "fixture eperm")

    monkeypatch.setattr(bootstrap_owner.os, "killpg", refuse_group_signal)

    assert (
        bootstrap_owner._terminate_and_wait(
            process, allow_natural_exit_eperm=True
        )
        == 0
    )
    assert process.wait_calls == 1


@pytest.mark.parametrize("wait_result", [-signal.SIGKILL, "timeout"])
def test_effective_runner_refuses_eperm_without_natural_zero_exit(
    bootstrap_owner, monkeypatch: pytest.MonkeyPatch, wait_result: int | str,
) -> None:
    class UncertainExit:
        pid = 123456
        wait_calls = 0

        def wait(self, *, timeout):
            assert timeout == 1
            self.wait_calls += 1
            if wait_result == "timeout":
                raise bootstrap_owner.subprocess.TimeoutExpired("sshd", timeout)
            return wait_result

    process = UncertainExit()

    def refuse_group_signal(_pid, _signal):
        raise PermissionError(errno.EPERM, "fixture eperm")

    monkeypatch.setattr(bootstrap_owner.os, "killpg", refuse_group_signal)

    with pytest.raises(
        bootstrap_owner.BootstrapOwnershipError,
        match="effective-validation-uncertain",
    ):
        bootstrap_owner._terminate_and_wait(
            process, allow_natural_exit_eperm=True
        )
    assert process.wait_calls == 1


def test_effective_runner_refuses_leader_that_closes_stdout_before_exit(
    bootstrap_owner,
    ssh_config: Path,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    output = (
        b"port 22\npasswordauthentication no\nkbdinteractiveauthentication no\n"
        b"permitrootlogin no\npubkeyauthentication yes\nx11forwarding no\n"
    )
    stub = tmp_path / "early-stdout-close-sshd"
    stub.write_text(
        "#!/bin/sh\n"
        f"printf %s {shlex.quote(output.decode('ascii'))}\n"
        "exec 1>&-\n"
        "sleep 10\n",
        encoding="ascii",
    )
    stub.chmod(0o755)
    monkeypatch.setattr(bootstrap_owner, "SSHD", str(stub))
    monkeypatch.setattr(bootstrap_owner, "COMMAND_TIMEOUT", 5.0)

    started = time.monotonic()
    with pytest.raises(
        bootstrap_owner.BootstrapOwnershipError,
        match="effective-validation-failed",
    ):
        bootstrap_owner.normalize(ssh_config, "22")

    assert time.monotonic() - started < 2


@pytest.mark.parametrize("failure_point", ["constructor", "register"])
def test_effective_runner_reaps_once_when_selector_setup_fails(
    bootstrap_owner,
    ssh_config: Path,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    failure_point: str,
) -> None:
    ready = tmp_path / "selector-child-ready"
    sentinel = tmp_path / "selector-descendant-survived"
    stub = tmp_path / f"selector-{failure_point}-sshd"
    stub.write_text(
        "#!/bin/sh\n"
        f"(sleep 0.2; touch {shlex.quote(str(sentinel))}) &\n"
        f"printf ready > {shlex.quote(str(ready))}\n"
        "sleep 10\n",
        encoding="ascii",
    )
    stub.chmod(0o755)
    monkeypatch.setattr(bootstrap_owner, "SSHD", str(stub))
    cloud = ssh_config / "sshd_config.d" / CLOUD
    cloud.write_bytes(b"# cloud\nPasswordAuthentication no\n")
    cloud.chmod(0o640)
    before = _rollback_records(ssh_config)
    processes = []
    real_popen = bootstrap_owner.subprocess.Popen
    real_selector = bootstrap_owner.selectors.DefaultSelector

    class ObservedProcess:
        def __init__(self, process):
            self._process = process
            self.stdout = process.stdout
            self.pid = process.pid
            self.wait_calls = 0

        def wait(self, *args, **kwargs):
            self.wait_calls += 1
            return self._process.wait(*args, **kwargs)

    def observed_popen(*args, **kwargs):
        process = ObservedProcess(real_popen(*args, **kwargs))
        processes.append(process)
        return process

    def wait_until_child_started() -> None:
        deadline = time.monotonic() + 5
        while not ready.exists() and time.monotonic() < deadline:
            time.sleep(0.005)
        assert ready.exists()

    if failure_point == "constructor":
        def failing_selector():
            wait_until_child_started()
            raise OSError("injected selector constructor failure")

        monkeypatch.setattr(
            bootstrap_owner.selectors, "DefaultSelector", failing_selector
        )
    else:
        class FailingRegisterSelector:
            def __init__(self):
                self._selector = real_selector()

            def register(self, *_args, **_kwargs):
                wait_until_child_started()
                raise OSError("injected selector register failure")

            def close(self):
                self._selector.close()

        monkeypatch.setattr(
            bootstrap_owner.selectors,
            "DefaultSelector",
            FailingRegisterSelector,
        )
    monkeypatch.setattr(bootstrap_owner.subprocess, "Popen", observed_popen)

    with pytest.raises(
        bootstrap_owner.BootstrapOwnershipError,
        match="effective-validation-failed",
    ):
        bootstrap_owner.normalize(ssh_config, "22")

    assert _rollback_records(ssh_config) == before
    assert len(processes) == 1
    assert processes[0].wait_calls == 1
    assert processes[0]._process.returncode is not None
    time.sleep(0.3)
    assert not sentinel.exists()


@pytest.mark.parametrize(
    "inherit_stdout,expected_error",
    [(True, "effective-validation-timeout"), (False, None)],
    ids=["inherited-pipe-timeout", "closed-pipe-success"],
)
def test_effective_runner_always_terminates_its_owned_process_group(
    bootstrap_owner,
    ssh_config: Path,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    inherit_stdout: bool,
    expected_error: str | None,
) -> None:
    sentinel = tmp_path / "descendant-survived"
    pidfile = tmp_path / "descendant-pid"
    output = (
        b"port 22\npasswordauthentication no\nkbdinteractiveauthentication no\n"
        b"permitrootlogin no\npubkeyauthentication yes\nx11forwarding no\n"
    )
    redirect = "" if inherit_stdout else "exec >/dev/null 2>&1; "
    stub = tmp_path / f"descendant-sshd-{inherit_stdout}"
    child_command = (
        f"sleep 10; touch {shlex.quote(str(sentinel))}"
    )
    stub.write_text(
        "#!/bin/sh\n"
        f"({redirect}/bin/sh -c {shlex.quote(child_command)}) &\n"
        f"printf '%s\\n' \"$!\" > {shlex.quote(str(pidfile))}\n"
        f"printf %s {shlex.quote(output.decode('ascii'))}\n"
        "exit 0\n",
        encoding="ascii",
    )
    stub.chmod(0o755)
    monkeypatch.setattr(bootstrap_owner, "SSHD", str(stub))
    monkeypatch.setattr(bootstrap_owner, "COMMAND_TIMEOUT", 5.0)
    real_killpg = bootstrap_owner.os.killpg
    group_kills: list[int] = []

    def observed_killpg(pid, group_signal):
        real_killpg(pid, group_signal)
        group_kills.append(pid)

    monkeypatch.setattr(bootstrap_owner.os, "killpg", observed_killpg)

    if expected_error is None:
        assert bootstrap_owner.normalize(ssh_config, "22") is True
    else:
        with pytest.raises(bootstrap_owner.BootstrapOwnershipError, match=expected_error):
            bootstrap_owner.normalize(ssh_config, "22")

    child_pid = int(pidfile.read_text())
    deadline = time.monotonic() + 1
    while True:
        status = subprocess.run(
            ["ps", "-o", "stat=", "-p", str(child_pid)],
            check=False,
            capture_output=True,
            text=True,
        )
        state = status.stdout.strip()
        if status.returncode != 0 or not state or state.startswith("Z"):
            child_active = False
            break
        if time.monotonic() >= deadline:
            child_active = True
            os.kill(child_pid, signal.SIGKILL)
            break
        time.sleep(0.01)
    assert child_active is False
    assert group_kills
    assert not sentinel.exists()


def _publish_boundary_child_status(
    bootstrap_owner,
    ssh_config: Path,
    *,
    boundary: str,
    target: str,
    port: str,
) -> int:
    child = os.fork()
    if child == 0:
        try:
            def terminate(phase: str, name: str) -> None:
                if (phase, name) == (boundary, target):
                    os.kill(os.getpid(), signal.SIGKILL)

            bootstrap_owner.PUBLISH_BOUNDARY_HOOK = terminate
            bootstrap_owner.normalize(ssh_config, port)
        except Exception:
            # A pre-boundary refusal must terminate this fork.  Letting it
            # return into pytest would duplicate the remainder of the suite.
            os._exit(92)
        os._exit(91)
    waited, status = os.waitpid(child, 0)
    assert waited == child
    return status


def test_publish_boundary_child_contains_a_preboundary_refusal(
    bootstrap_owner, ssh_config: Path,
) -> None:
    status = _publish_boundary_child_status(
        bootstrap_owner,
        ssh_config,
        boundary="file-fsync",
        target=BOOT,
        port="invalid",
    )

    assert os.WIFEXITED(status)
    assert os.WEXITSTATUS(status) == 92


@pytest.mark.parametrize("target", [BOOT, MANAGED, CLOUD])
@pytest.mark.parametrize("boundary", ["file-fsync", "replace", "directory-fsync"])
def test_process_death_at_every_publish_boundary_is_nonweakening_and_converges(
    bootstrap_owner, ssh_config: Path, target: str, boundary: str,
) -> None:
    fragments = ssh_config / "sshd_config.d"
    cloud = fragments / CLOUD
    cloud.write_bytes(b"# cloud\nPasswordAuthentication no\n")
    cloud.chmod(0o644)

    status = _publish_boundary_child_status(
        bootstrap_owner,
        ssh_config,
        boundary=boundary,
        target=target,
        port="22",
    )

    assert os.WIFSIGNALED(status) and os.WTERMSIG(status) == signal.SIGKILL

    boot = fragments / BOOT
    managed = fragments / MANAGED
    if boot.exists():
        assert boot.read_bytes() == bootstrap_owner._boot_content("22")
    if managed.exists():
        assert boot.exists()
        assert managed.read_bytes() == bootstrap_owner.MANAGED_CONTENT
    if b"PasswordAuthentication no" not in cloud.read_bytes():
        assert boot.exists()
    residues = tuple(fragments.glob(".bootstrap-sshd-*"))
    assert len(residues) <= 1

    bootstrap_owner.normalize(ssh_config, "22")

    assert boot.read_bytes() == bootstrap_owner._boot_content("22")
    assert managed.read_bytes() == bootstrap_owner.MANAGED_CONTENT
    assert cloud.read_bytes() == b"# cloud\n"
    assert not tuple(fragments.glob(".bootstrap-sshd-*"))


@pytest.mark.parametrize("ssh_port", ["", "0", "65536", "022", "22 ", 22])
def test_ssh_port_must_be_a_canonical_bounded_string(
    bootstrap_owner, ssh_config: Path, ssh_port,
) -> None:
    before = _records(ssh_config)
    with pytest.raises(bootstrap_owner.BootstrapOwnershipError, match="invalid-port"):
        bootstrap_owner.normalize(ssh_config, ssh_port)
    assert _records(ssh_config) == before


def test_all_renderers_embed_the_exact_bootstrap_owner() -> None:
    rendered = subprocess.run(
        [sys.executable, str(RENDERER)],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    config = yaml.safe_load(rendered)
    helper = next(
        item for item in config["write_files"]
        if item["path"] == "/usr/local/libexec/vpn-bootstrap-sshd-ownership.py"
    )
    assert base64.b64decode(helper["content"]) == BOOTSTRAP_OWNER.read_bytes()
    assert helper["encoding"] == "b64"
    assert helper["permissions"] == "0700"
    for provider in ("upcloud", "hetzner", "scaleway", "vultr"):
        source = (REPO_ROOT / "terraform" / "providers" / provider / "main.tf").read_text()
        assert 'bootstrap_ssh_ownership_b64 = filebase64("${path.module}/../../shared/bootstrap-sshd-ownership.py")' in source


def test_bootstrap_marker_depends_on_validated_successful_ssh_reload(
    tmp_path: Path,
) -> None:
    rendered = subprocess.run(
        [sys.executable, str(RENDERER)],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    rendered_config = yaml.safe_load(rendered)
    assert rendered_config["users"][1]["name"] == "deploy"
    hardening = next(
        item
        for item in rendered_config["write_files"]
        if item["path"] == "/usr/local/libexec/vpn-bootstrap-sshd-ownership.py"
    )
    assert base64.b64decode(hardening["content"]) == BOOTSTRAP_OWNER.read_bytes()
    assert "${" not in rendered

    cloud_config = yaml.safe_load(TEMPLATE.read_text(encoding="utf-8"))
    commands = cloud_config["runcmd"]

    assert len(commands) == 1
    assert commands[0][:2] == ["sh", "-c"]
    command = commands[0][2]
    assert "/usr/bin/python3 -I -B /usr/local/libexec/vpn-bootstrap-sshd-ownership.py" in command
    assert command.index("install -d -m 0755 /run/sshd") < command.index(
        "vpn-bootstrap-sshd-ownership.py"
    )
    assert command.index("vpn-bootstrap-sshd-ownership.py") < command.index("sshd -t")
    assert command.index("install -d -m 0755 /run/sshd") < command.index("sshd -t")
    assert command.index("sshd -t") < command.index("systemctl reload ssh")
    assert command.index("systemctl reload ssh") < command.index(f"touch {MARKER}")

    sshd = tmp_path / "sshd"
    sshd.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    sshd.chmod(0o755)
    systemctl = tmp_path / "systemctl"
    systemctl.write_text('#!/bin/sh\nexit "${SYSTEMCTL_RC:?}"\n', encoding="utf-8")
    systemctl.chmod(0o755)
    owner = tmp_path / "bootstrap-owner"
    owner.write_text('#!/bin/sh\nexit "${OWNER_RC:?}"\n', encoding="utf-8")
    owner.chmod(0o755)
    marker = tmp_path / "bootstrap.done"
    executable = (
        command.replace("install -d -m 0755 /run/sshd && ", "")
        .replace(
            "/usr/bin/python3 -I -B /usr/local/libexec/vpn-bootstrap-sshd-ownership.py "
            "--config-dir /etc/ssh --ssh-port ${ssh_port}",
            str(owner),
        )
        .replace("/usr/sbin/sshd", str(sshd))
        .replace("systemctl", str(systemctl))
        .replace(MARKER, str(marker))
    )

    owner_failed = subprocess.run(
        ["sh", "-c", executable],
        env={**os.environ, "OWNER_RC": "1", "SYSTEMCTL_RC": "0"},
        check=False,
    )
    assert owner_failed.returncode != 0
    assert not marker.exists()

    failed = subprocess.run(
        ["sh", "-c", executable],
        env={**os.environ, "OWNER_RC": "0", "SYSTEMCTL_RC": "1"},
        check=False,
    )
    assert failed.returncode != 0
    assert not marker.exists()

    succeeded = subprocess.run(
        ["sh", "-c", executable],
        env={**os.environ, "OWNER_RC": "0", "SYSTEMCTL_RC": "0"},
        check=False,
    )
    assert succeeded.returncode == 0
    assert marker.exists()

    already_completed = subprocess.run(
        ["sh", "-c", executable],
        env={**os.environ, "OWNER_RC": "1", "SYSTEMCTL_RC": "1"},
        check=False,
    )
    assert already_completed.returncode == 0
    assert marker.exists()
